### ISSUE TITLE
As a game user, I want to choose my play style and strategies based on the situation so that I can use strategies during gameplay

### ISSUE THREAD

**Issue by ghost** [Software-Engineering-2-Pixel-Studio/pixelstudio#10]
Core feature: Playstyle and strategy select option through the specialized class system - sprint 4

Story Points: 4
Risk: Medium

## Acceptance Test # 1 - Player Choice: 
1. Start the game
2. Create a room
               2.1 Choose one of the options of the class for the specific playstyle
                              2.1.1. Mage Class, or
                              2.1.2 Defender Class
3. Check the towers displayed
         
### During the game: 

The Player should wee the list of towers specific for their class:
- Mage class will have Base Tower, Fire Tower, and Light Tower
- Defender class will have Base Tower, Slow Tower, and Light Tower

## Acceptance Test # 2 - Tower Debuffs: 
1. Start the game
2. Place towers on the map prior to the beginning of the wave
               2.1 Choose the type of tower you want to be placed
                              2.1.1. Fire Tower: Does damage to the enemies
                              2.1.2 Slow Tower: Does less damage, but reduces the speed of the enemy
                              2.1.3 Light Tower: Does more damage to the enemies than all of the other towers
3. Start the wave
         
### During the wave: 

- The Towers will apply a specific amount of damage to the enemies and apply debuffs if applicable for the type
-  Different positionings of the towers of various types may make it easier to eliminate the enemies

**Comment by Phamhhuy** [comment]
Specialized Class System feature is implemented which including 2 classes for players to choose : Mage and Defender.
Where Mage focus on doing element damage to monsters. Meanwhile, Defender focus on slowing down monsters.
