### ISSUE TITLE
As a game user, I want to level up or upgrade my towers so it's easier for me to defend the base

### ISSUE THREAD

**Issue by ghost** [Software-Engineering-2-Pixel-Studio/pixelstudio#4]
Core feature: towers' in-game level up(upgrade) system - sprint 2

Story Points: 5 (For both level-up and tower upgrade system)
Risk: Medium

## Acceptance Test # 1 - Upgrade: 
1. Start the game
2. Place towers on the map prior to the beginning of the wave
3. Click on the Tower you want to upgrade. When you have enough tech points, you should be able to upgrade it
4. When you're hovering the upgrade button, it should display the tower name and stats and how much it will improve
5. Start the wave

### During the wave: 

- The Towers will apply more damage to the enemies, which causes the enemies to die more quickly
- If tech upgraded, the tower should fire faster and have faster projectile

## Acceptance Test # 2 - Level Up: 
1. Start the game
2. Place towers on the map prior to the beginning of the wave
3. Start the wave
4. Once an enemy gets killed, you should get an experience point
5. Once you reached the max exp for the level, get a tech point to be used for upgrade attack cooldown and projectile speed of the tower
6. Click on the Tower you want to upgrade. When you have enough tech points, you should be able to upgrade it
7. When you're hovering the tech upgrade button, it should display the tower name and stats and how much it will improve
         
### During the wave: 

- The Towers will apply more damage to the enemies, which causes the enemies to die more quickly
- If tech upgraded, the tower should fire faster and have faster projectile

**Comment by Hintaycl** [comment]
Player leveling system is added. Along with upgrading towers from tech points which you can get from leveling up. Also added upgrading of towers through money
