### ISSUE TITLE
[TASK] implement auth in web app and communicate with WebGL

### ISSUE THREAD

**Issue by ghost** [Software-Engineering-2-Pixel-Studio/pixelstudio#50]
Details: implement auth in web app and communicate with WebGL

Story Points: 3
Risk: High

## Acceptance Test:
- Allow creation of accounts and connection of users through WebGL and Unity

**Comment by Hintaycl** [comment]
Removed as this is not part of the features now because the member implementing the web part left the team. The removal of web development related features were approved by the professor.
