### ISSUE TITLE
[DOCUMENTATION] Create a sequence diagram for Tower Upgrade and Playstyle user story

### ISSUE THREAD

**Issue by Hintaycl** [Software-Engineering-2-Pixel-Studio/pixelstudio#56]
Details: For sprint 2, design and create sequence diagrams for each user story
Acceptance criteria: Create a wiki page for all of the user stories' sequence diagram

Story Points: 3
Risk: High

**Comment by Phamhhuy** [comment]
Need to added more sequence diagram
