### ISSUE TITLE
Refactory_LevelManagment_Script

### ISSUE THREAD

**Issue by Phamhhuy** [Software-Engineering-2-Pixel-Studio/pixelstudio#63]
Refactory LevelManagement Script
-Code clean up and code refactor
-Also fix camera movement
-Change some of the assets

Story Point: 3 points
Risk: High

## Acceptance Test:
-All working components should still work
-Allow camera movement with WASD
-Some assets are changed for tiles, towers, base and spawn point

**Comment by Hintaycl** [comment]
This is done
